package main

import (
	"fmt"
	"os"
	"regexp"
	"strings"
)

// config.php is generated by install.sh (Lightweight-DNS / Lightweight-Hosting)
const defaultConfigPath = "/var/www/admin_panel/config.php"

type DBConfig struct {
	User string
	Pass string
	Host string
	Name string
}

func parsePHPConfig(path string, key string) string {
	content, err := os.ReadFile(path)
	if err != nil {
		return ""
	}
	re := regexp.MustCompile(`define\s*\(\s*['"]` + key + `['"]\s*,\s*['"](.*?)['"]\s*\)`)
	matches := re.FindStringSubmatch(string(content))
	if len(matches) > 1 {
		return matches[1]
	}
	return ""
}

// loadDBConfig reads the DB credentials from the config.php that the
// installer generates. Environment variables (DB_USER, DB_PASS, DB_HOST,
// DB_NAME, CONFIG_PATH) take precedence over the file.
func loadDBConfig() (DBConfig, error) {
	configPath := os.Getenv("CONFIG_PATH")
	if configPath == "" {
		configPath = defaultConfigPath
	}

	get := func(key string) string {
		if v := os.Getenv(key); v != "" {
			return v
		}
		return parsePHPConfig(configPath, key)
	}

	cfg := DBConfig{
		User: get("DB_USER"),
		Pass: get("DB_PASS"),
		Host: get("DB_HOST"),
		Name: get("DB_NAME"),
	}

	if cfg.User == "" || cfg.Pass == "" {
		return cfg, fmt.Errorf("DB credentials not found: set DB_USER/DB_PASS env vars or install via install.sh so %s exists", configPath)
	}

	if cfg.Host == "" {
		cfg.Host = "127.0.0.1"
	}
	if !strings.Contains(cfg.Host, ":") {
		cfg.Host += ":3306"
	}
	if cfg.Name == "" {
		cfg.Name = cfg.User
	}

	return cfg, nil
}
