package main

import (
	"database/sql"
	"fmt"
	"log"
	"os"
	"os/exec"
	"regexp"
	"strings"
	"time"
)

const (
	zonesDir      = "/etc/bind/zones"
	autoZonesConf = "/etc/bind/autogenerated_zones.conf"
)

func runEngine(db *sql.DB) {
	ticker := time.NewTicker(60 * time.Second)
	defer ticker.Stop()

	// Run once immediately
	processRequests(db)

	for range ticker.C {
		processRequests(db)
	}
}

// maxRequestAttempts bounds the retries of a single request. Past it the row stays
// in 'error' for a human to look at, instead of spinning forever.
const maxRequestAttempts = 5

// requeueStalledRequests brings back work that would otherwise be lost forever: the
// main loop only ever selected 'pending', so a row left in 'processing' by a crash,
// or parked in 'error' by a transient named-checkconf failure, was never retried.
//
// Only recent rows are retried. The queue is a log going back months, and replaying
// old entries would rebuild zones from requests the current database state has long
// since superseded — on a node upgrading to this build, every historical failure
// would fire at once. Anything older than the window is stale by definition, and
// reconciling it is the panel's sync job, not a blind replay.
func requeueStalledRequests(db *sql.DB) {
	res, err := db.Exec(`
		UPDATE sys_dns_requests
		SET status = 'pending'
		WHERE status = 'processing'
		  AND attempts < ?
		  AND request_date > NOW() - INTERVAL 1 DAY
		  AND (started_at IS NULL OR started_at < NOW() - INTERVAL 10 MINUTE)`, maxRequestAttempts)
	if err != nil {
		log.Println("Error requeueing stalled requests:", err)
	} else if n, _ := res.RowsAffected(); n > 0 {
		log.Printf("Requeued %d stalled request(s)", n)
	}

	res, err = db.Exec(`
		UPDATE sys_dns_requests
		SET status = 'pending'
		WHERE status = 'error'
		  AND attempts < ?
		  AND request_date > NOW() - INTERVAL 1 DAY
		  AND (processed_date IS NULL OR processed_date < NOW() - INTERVAL 5 MINUTE)`, maxRequestAttempts)
	if err != nil {
		log.Println("Error requeueing failed requests:", err)
	} else if n, _ := res.RowsAffected(); n > 0 {
		log.Printf("Requeued %d failed request(s) for retry", n)
	}
}

func processRequests(db *sql.DB) {
	requeueStalledRequests(db)

	rows, err := db.Query("SELECT id, action, domain, status FROM sys_dns_requests WHERE status = 'pending' ORDER BY id ASC")
	if err != nil {
		log.Println("Error fetching requests:", err)
		return
	}
	defer rows.Close()

	var requests []DNSRequest
	for rows.Next() {
		var req DNSRequest
		if err := rows.Scan(&req.ID, &req.Action, &req.Domain, &req.Status); err != nil {
			log.Println("Error scanning request:", err)
			continue
		}
		requests = append(requests, req)
	}

	if len(requests) == 0 {
		return
	}

	reloadNeeded := false

	// Ensure dirs exist
	_ = os.MkdirAll(zonesDir, 0755)

	for _, req := range requests {
		db.Exec("UPDATE sys_dns_requests SET status = 'processing', started_at = NOW(), attempts = attempts + 1 WHERE id = ?", req.ID)

		zoneFilePath := fmt.Sprintf("%s/db.%s", zonesDir, req.Domain)

		if req.Action == "delete" {
			os.Remove(zoneFilePath)
			removeFromAutoConf(req.Domain)
			db.Exec("DELETE FROM sys_dns_zones WHERE domain = ?", req.Domain)
			db.Exec("UPDATE sys_dns_requests SET status = 'completed', processed_date = NOW() WHERE id = ?", req.ID)
			reloadNeeded = true
		} else { // add or update
			var zoneID int
			err := db.QueryRow("SELECT id FROM sys_dns_zones WHERE domain = ?", req.Domain).Scan(&zoneID)
			if err == sql.ErrNoRows {
				res, _ := db.Exec("INSERT INTO sys_dns_zones (domain, zone_file_path, is_active) VALUES (?, ?, 1)", req.Domain, zoneFilePath)
				zid, _ := res.LastInsertId()
				zoneID = int(zid)
			}

			// Generate zone file
			serial := time.Now().Format("20060102") + "01"
			if oldSerialStr := readZoneSerial(zoneFilePath); oldSerialStr != "" {
				// Only increment if the date part matches today
				if strings.HasPrefix(oldSerialStr, time.Now().Format("20060102")) {
					var old int
					fmt.Sscanf(oldSerialStr, "%d", &old)
					serial = fmt.Sprintf("%d", old+1)
				}
			}

			generateZoneFile(db, zoneID, req.Domain, zoneFilePath, serial)
			addedToConf := addToAutoConf(req.Domain, zoneFilePath)

			// Check config
			cmd := exec.Command("named-checkconf", "/etc/bind/named.conf")
			out, err := cmd.CombinedOutput()
			if err != nil {
				// The zone block we just appended is what named.conf is choking on.
				// Leaving it there would keep BIND from reloading *anything*, so we
				// take back exactly what we added and let the retry try again.
				if addedToConf {
					removeFromAutoConf(req.Domain)
				}
				db.Exec("UPDATE sys_dns_requests SET status = 'error', error_log = ?, processed_date = NOW() WHERE id = ?", string(out), req.ID)
			} else {
				db.Exec("UPDATE sys_dns_requests SET status = 'completed', processed_date = NOW() WHERE id = ?", req.ID)
				reloadNeeded = true
			}
		}
	}

	if reloadNeeded {
		log.Println("Reloading BIND...")
		exec.Command("rndc", "reload").Run()
	}
}

var serialRe = regexp.MustCompile(`\(\s*(\d{10})\s+`)

// readZoneSerial extracts the serial from the SOA line of an existing zone file,
// e.g. "( 2026071501 3600 ...". Returns "" when the file is missing or has none.
func readZoneSerial(path string) string {
	b, err := os.ReadFile(path)
	if err != nil {
		return ""
	}
	matches := serialRe.FindStringSubmatch(string(b))
	if len(matches) > 1 {
		return matches[1]
	}
	return ""
}

func generateZoneFile(db *sql.DB, zoneID int, domain, path, serial string) {
	content, err := buildZoneFile(db, zoneID, domain, serial)
	if err != nil {
		log.Println("Error fetching records:", err)
		return
	}
	os.WriteFile(path, []byte(content), 0644)
}

// buildZoneFile renders the BIND9 zone file for a zone without touching disk, so the
// same output the engine writes can be served by /api-dns/zone/{domain}/export.
func buildZoneFile(db *sql.DB, zoneID int, domain, serial string) (string, error) {
	rows, err := db.Query("SELECT name, type, content, ttl, priority FROM sys_dns_records WHERE zone_id = ? ORDER BY sort_order ASC, id ASC", zoneID)
	if err != nil {
		return "", err
	}
	defer rows.Close()

	var sb strings.Builder
	sb.WriteString(fmt.Sprintf("; Autogenerated Zone for %s\n", domain))
	sb.WriteString(fmt.Sprintf("$ORIGIN %s.\n", domain))
	sb.WriteString("$TTL 3600\n\n")

	var records []DNSRecord
	for rows.Next() {
		var r DNSRecord
		rows.Scan(&r.Name, &r.Type, &r.Content, &r.TTL, &r.Priority)
		records = append(records, r)
	}

	// SOA handling
	hasSOA := false
	for _, r := range records {
		if r.Type == "SOA" {
			soaContent := strings.Replace(r.Content, "{SERIAL}", serial, 1)
			sb.WriteString(fmt.Sprintf("@\tIN\tSOA\t%s\n", soaContent))
			hasSOA = true
			break
		}
	}
	if !hasSOA {
		sb.WriteString(fmt.Sprintf("@\tIN\tSOA\tns1.%s. hostmaster.%s. %s 3600 1800 604800 86400\n", domain, domain, serial))
	}

	// Other records
	for _, r := range records {
		if r.Type == "SOA" {
			continue
		}
		prio := ""
		if (r.Type == "MX" || r.Type == "SRV") && r.Priority.Valid {
			prio = fmt.Sprintf("%d\t", r.Priority.Int32)
		}

		content := r.Content
		if r.Type == "TXT" {
			// Remove any existing quotes to normalize
			content = strings.TrimSpace(content)
			if strings.HasPrefix(content, "\"") && strings.HasSuffix(content, "\"") {
				content = content[1 : len(content)-1]
			}
			
			// Split into 255-byte chunks
			var chunks []string
			for len(content) > 0 {
				chunkSize := 255
				if len(content) < 255 {
					chunkSize = len(content)
				}
				chunks = append(chunks, "\"" + content[:chunkSize] + "\"")
				content = content[chunkSize:]
			}
			content = strings.Join(chunks, " ")
		}

		sb.WriteString(fmt.Sprintf("%s\t%d\tIN\t%s\t%s%s\n", r.Name, r.TTL, r.Type, prio, content))
	}

	return sb.String(), nil
}

// addToAutoConf reports whether it actually appended a new zone block, so the caller
// can undo exactly what it added if named-checkconf then rejects the config.
func addToAutoConf(domain, path string) bool {
	b, _ := os.ReadFile(autoZonesConf)
	content := string(b)
	target := fmt.Sprintf("zone \"%s\"", domain)
	if strings.Contains(content, target) {
		return false
	}
	appendStr := fmt.Sprintf("zone \"%s\" {\n\ttype master;\n\tfile \"%s\";\n};\n", domain, path)
	f, _ := os.OpenFile(autoZonesConf, os.O_APPEND|os.O_CREATE|os.O_WRONLY, 0644)
	defer f.Close()
	f.WriteString(appendStr)
	return true
}

func removeFromAutoConf(domain string) {
	// Simplistic remove (in a real scenario, use regex or proper parsing)
	b, _ := os.ReadFile(autoZonesConf)
	content := string(b)
	targetStart := fmt.Sprintf("zone \"%s\" {", domain)
	idx := strings.Index(content, targetStart)
	if idx != -1 {
		endIdx := strings.Index(content[idx:], "};")
		if endIdx != -1 {
			newContent := content[:idx] + content[idx+endIdx+2:]
			// clean up trailing newlines if any
			os.WriteFile(autoZonesConf, []byte(newContent), 0644)
		}
	}
}
