#!/bin/bash

# ==========================================================================
# Lightweight-Hosting-DNS Installer - Complemento DNS
# Hardware Target: 1vCore, 1GB RAM
# ==========================================================================

# Colores para la salida
GREEN='\033[0;32m'
RED='\033[0;31m'
YELLOW='\033[1;33m'
NC='\033[0m'

printf "${GREEN}Iniciando instalación ultra-ligera del servidor DNS (Lightweight-Hosting-DNS)...${NC}\n"

# 1. Verificación de usuario root
if [ "$EUID" -ne 0 ]; then 
    printf "${RED}Por favor, ejecuta como root${NC}\n"
    exit 1
fi

# 2. Comprobar si existe Lightweight-Hosting configurado
ADMIN_PATH="/var/www/admin_panel"
CONFIG_FILE="$ADMIN_PATH/config.php"
ENGINE_PATH="/usr/local/bin/hosting"
API_PATH="/var/www/api-dns"

mkdir -p "$ENGINE_PATH"
mkdir -p "$API_PATH"

if [ -f "$CONFIG_FILE" ]; then
    printf "${GREEN}Detectada instalación de Lightweight-Hosting. Reutilizando configuración de bases de datos.${NC}\n"
    DB_PASS=$(grep "'DB_PASS'" "$CONFIG_FILE" | cut -d"'" -f4)
    DB_USER=$(grep "'DB_USER'" "$CONFIG_FILE" | cut -d"'" -f4)
    DB_NAME=$(grep "'DB_NAME'" "$CONFIG_FILE" | cut -d"'" -f4)
    HAS_LWH=true
else
    printf "${YELLOW}Lightweight-Hosting no detectado. Se preparará un entorno standalone...${NC}\n"
    HAS_LWH=false
    DB_USER="dbadmin"
    DB_NAME="dbadmin"
    DB_PASS=$(openssl rand -base64 18)
fi

# 3. Instalación de paquetes de Base de Datos y Web si no existen
printf "${YELLOW}Verificando dependencias del sistema...${NC}\n"
apt update -y

# Instalar PHP y MariaDB si son necesarios (en modo standalone)
if ! command -v mariadb >/dev/null 2>&1; then
    printf "${YELLOW}Instalando MariaDB (Stand-alone)...${NC}\n"
    apt install -y mariadb-server
    systemctl start mariadb
    
    ROOT_DB_PASS_FILE="/root/.hosting_db_root"
    if [ -f "$ROOT_DB_PASS_FILE" ]; then
        DB_ROOT_PASS=$(cat "$ROOT_DB_PASS_FILE")
    else
        DB_ROOT_PASS=$(openssl rand -base64 24)
        echo "$DB_ROOT_PASS" > "$ROOT_DB_PASS_FILE"
        chmod 600 "$ROOT_DB_PASS_FILE"
    fi
    
    # Asegurar root de MariaDB (si podemos acceder sin contraseña)
    if mariadb -e "status" >/dev/null 2>&1; then
        mariadb -e "ALTER USER 'root'@'localhost' IDENTIFIED BY '$DB_ROOT_PASS';"
    fi
    
    # Crear auth temporal para operar
    cat <<EOF > /root/.my.cnf
[client]
user=root
password=$DB_ROOT_PASS
EOF
    chmod 600 /root/.my.cnf
    
    # Crear BD y usuario si es standalone
    mariadb -e "CREATE DATABASE IF NOT EXISTS \`${DB_NAME}\`;"
    mariadb -e "DROP USER IF EXISTS '${DB_USER}'@'127.0.0.1';"
    mariadb -e "CREATE USER '${DB_USER}'@'127.0.0.1' IDENTIFIED BY '${DB_PASS}';"
    mariadb -e "GRANT ALL PRIVILEGES ON \`${DB_NAME}\`.* TO '${DB_USER}'@'127.0.0.1';"
    mariadb -e "FLUSH PRIVILEGES;"
    
    # Limpiar auth temporal
    rm -f /root/.my.cnf
    
    # Generar config.php mínimo para la API standalone
    mkdir -p "$ADMIN_PATH"
    cat <<EOF > "$CONFIG_FILE"
<?php
define('DB_HOST', '127.0.0.1');
define('DB_NAME', '$DB_NAME');
define('DB_USER', '$DB_USER');
define('DB_PASS', '$DB_PASS');

function getPDO() {
    static \$pdo;
    if (!\$pdo) {
        \$pdo = new PDO("mysql:host=" . DB_HOST . ";dbname=" . DB_NAME, DB_USER, DB_PASS, [
            PDO::ATTR_ERRMODE => PDO::ERRMODE_EXCEPTION,
            PDO::ATTR_DEFAULT_FETCH_MODE => PDO::FETCH_ASSOC
        ]);
    }
    return \$pdo;
}
?>
EOF
fi

if ! command -v php >/dev/null 2>&1; then
    printf "${YELLOW}Instalando PHP ligero (cli & fpm)...${NC}\n"
    apt install -y php-cli php-mysql php-fpm apache2
    a2enmod proxy_fcgi setenvif rewrite
    systemctl restart apache2
fi

# 4. Instalación del Servidor DNS (BIND9)
printf "${YELLOW}Instalando BIND9...${NC}\n"
apt install -y bind9 bind9utils bind9-doc dnsutils

# Configurar autoloader de zonas
BIND_ZONES_DIR="/etc/bind/zones"
AUTO_ZONES_FILE="/etc/bind/autogenerated_zones.conf"

mkdir -p "$BIND_ZONES_DIR"
touch "$AUTO_ZONES_FILE"
chown -R bind:bind "$BIND_ZONES_DIR"

# Incluir zonas dinámicas en BIND si no está ya
if ! grep -q "autogenerated_zones.conf" /etc/bind/named.conf.local; then
    echo 'include "/etc/bind/autogenerated_zones.conf";' >> /etc/bind/named.conf.local
fi

# 5. Desplegar Tablas DNS
printf "${YELLOW}Desplegando esquema DNS en MariaDB...${NC}\n"

mariadb -h 127.0.0.1 -u "$DB_USER" -p"$DB_PASS" -D "$DB_NAME" <<EOF
CREATE TABLE IF NOT EXISTS sys_dns_requests (
    id INT AUTO_INCREMENT PRIMARY KEY,
    action ENUM('add', 'delete') NOT NULL,
    domain VARCHAR(255) NOT NULL,
    target_ip VARCHAR(45) NULL,
    status ENUM('pending', 'processing', 'completed', 'error') DEFAULT 'pending',
    request_date DATETIME DEFAULT CURRENT_TIMESTAMP,
    processed_date DATETIME NULL,
    error_log TEXT NULL
);

CREATE TABLE IF NOT EXISTS sys_dns_zones (
    id INT AUTO_INCREMENT PRIMARY KEY,
    domain VARCHAR(255) UNIQUE NOT NULL,
    zone_file_path VARCHAR(255) NOT NULL,
    is_active BOOLEAN DEFAULT 1,
    created_at DATETIME DEFAULT CURRENT_TIMESTAMP,
    updated_at DATETIME DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP
);

CREATE TABLE IF NOT EXISTS sys_dns_records (
    id INT AUTO_INCREMENT PRIMARY KEY,
    zone_id INT NOT NULL,
    name VARCHAR(255) NOT NULL,
    type ENUM('SOA', 'NS', 'A', 'AAAA', 'CNAME', 'MX', 'TXT', 'SRV') NOT NULL,
    content VARCHAR(255) NOT NULL,
    ttl INT DEFAULT 3600,
    priority INT NULL,
    FOREIGN KEY (zone_id) REFERENCES sys_dns_zones(id) ON DELETE CASCADE
);
EOF

# 6. Configurar Cron Job
printf "${YELLOW}Configurando Cron Job para resolver DNS...${NC}\n"
CRON_SCRIPT="$ENGINE_PATH/sync_dns.php"

if ! crontab -l 2>/dev/null | grep -q "sync_dns.php"; then
    (crontab -l 2>/dev/null; echo "*/5 * * * * /usr/bin/php $CRON_SCRIPT > /dev/null 2>&1") | crontab -
    printf "${GREEN}Cron de sync_dns configurado.${NC}\n"
fi

# 7. Completado
systemctl restart bind9

printf "${GREEN}====================================================${NC}\n"
printf "${GREEN} INSTALACIÓN DNS COMPLETADA CON ÉXITO${NC}\n"
printf "${GREEN}====================================================${NC}\n"
if [ "$HAS_LWH" = false ]; then
    printf "${YELLOW}Stand-alone Setup: DB dbadmin guardada con pass: $DB_PASS${NC}\n"
fi
printf "Recuerda descargar/copiar los scripts PHP a $ENGINE_PATH y $API_PATH\n"
