<?php
/**
 * Lightweight-Hosting-DNS Engine: sync_dns.php
 * Script crontab (1 Core / 1GB RAM target)
 */

if (php_sapi_name() !== 'cli') {
    die("Solo ejecutable desde CLI.\n");
}

// 1. Lock para evitar concurrencia
$lockFile = sys_get_temp_dir() . '/sync_dns.lock';
$lockHandle = fopen($lockFile, 'w+');
if (!$lockHandle || !flock($lockHandle, LOCK_EX | LOCK_NB)) {
    die("Ya hay una instancia ejecutándose. Saliendo.\n");
}

// 2. Conexión a Base de Datos
$configFile = '/var/www/admin_panel/config.php';
if (file_exists($configFile)) {
    require_once $configFile;
} else {
    // Modo desarrollo / fallback local
    $localConfig = __DIR__ . '/../../config.php';
    if (file_exists($localConfig)) {
        require_once $localConfig;
    } else {
        die("Error: No config.php found.\n");
    }
}

$pdo = getPDO();
$zonesDir = '/etc/bind/zones';
$autoZonesConf = '/etc/bind/autogenerated_zones.conf';
$templateFile = __DIR__ . '/template.zone.php';

// Validar que los directorios existen
if (!is_dir($zonesDir)) {
    @mkdir($zonesDir, 0755, true);
}
if (!file_exists($autoZonesConf)) {
    @touch($autoZonesConf);
}

// 3. Obtener Tareas Pendientes Ordenadas
$stmt = $pdo->query("SELECT * FROM sys_dns_requests WHERE status = 'pending' ORDER BY id ASC");
$requests = $stmt->fetchAll();

if (empty($requests)) {
    flock($lockHandle, LOCK_UN);
    fclose($lockHandle);
    exit(0);
}

$reloadNeeded = false;

foreach ($requests as $req) {
    try {
        $id = $req['id'];
        $domain = $req['domain'];
        $action = $req['action']; // 'add' (which means create/update config) or 'delete'
        $zoneFilePath = $zonesDir . '/db.' . $domain;
        
        // Marcar en proceso
        $pdo->prepare("UPDATE sys_dns_requests SET status = 'processing' WHERE id = ?")->execute([$id]);
        
        if ($action === 'delete') {
            // Eliminar archivo
            if (file_exists($zoneFilePath)) {
                unlink($zoneFilePath);
            }
            
            // Eliminar de autogenerated_zones.conf
            $confContent = file_get_contents($autoZonesConf);
            $pattern = '/zone\s+"' . preg_quote($domain, '/') . '"\s+\{[^}]+\};\n?/s';
            if (preg_match($pattern, $confContent)) {
                $newConfContent = preg_replace($pattern, '', $confContent);
                file_put_contents($autoZonesConf, $newConfContent);
                $reloadNeeded = true;
            }
            
            // Eliminar también de sys_dns_zones / records cascade
            $pdo->prepare("DELETE FROM sys_dns_zones WHERE domain = ?")->execute([$domain]);
            
            // Marcar completado
            $pdo->prepare("UPDATE sys_dns_requests SET status = 'completed', processed_date = NOW() WHERE id = ?")->execute([$id]);
            
        } else { // $action === 'add' (Create or Update)
            
            // a) Asegurar que la zona existe en BBDD para no romper foreign keys si fue creado por update (aunque el endpoint lo hace)
            $zonaIdStmt = $pdo->prepare("SELECT id FROM sys_dns_zones WHERE domain = ?");
            $zonaIdStmt->execute([$domain]);
            $zona = $zonaIdStmt->fetch();
            
            if (!$zona) {
                $pdo->prepare("INSERT INTO sys_dns_zones (domain, zone_file_path, is_active) VALUES (?, ?, 1)")->execute([$domain, $zoneFilePath]);
                $zonaId = $pdo->lastInsertId();
            } else {
                $zonaId = $zona['id'];
            }
            
            // b) Recuperar Registros
            $recStmt = $pdo->prepare("SELECT * FROM sys_dns_records WHERE zone_id = ? ORDER BY sort_order ASC, id ASC");
            $recStmt->execute([$zonaId]);
            $records = $recStmt->fetchAll();
            
            // c) Generar Archivo a partir de Template
            $serial = date('Ymd') . '01'; // En prod real se autoincrementa. Serial simple por dia
            if (file_exists($zoneFilePath)) {
                // Leer serial anterior para aumentarlo y asegurar propagación
                $oldContent = file_get_contents($zoneFilePath);
                if (preg_match('/(\d{10})\s+;\s+Serial/i', $oldContent, $sm)) {
                    $oldSerial = (int)$sm[1];
                    $todayPrefix = (int)date('Ymd');
                    $oldPrefix = (int)substr($sm[1], 0, 8);
                    if ($todayPrefix == $oldPrefix) {
                        $serial = $oldSerial + 1;
                    }
                }
            }
            
            ob_start();
            include $templateFile;
            $zoneContent = ob_get_clean();
            file_put_contents($zoneFilePath, $zoneContent);
            
            // d) Añadir a autogenerated_zones.conf si no existe
            $confContent = file_get_contents($autoZonesConf);
            if (strpos($confContent, 'zone "' . $domain . '"') === false) {
                $zoneConfigBlock = "zone \"{$domain}\" {\n\ttype master;\n\tfile \"{$zoneFilePath}\";\n};\n";
                file_put_contents($autoZonesConf, $zoneConfigBlock, FILE_APPEND);
            }
            
            // e) Validar BIND Configuration
            $output = [];
            $return_var = 0;
            // Solo validamos la config general, asumiendo que el archivo en named.conf está ahí o el local está ok
            exec("named-checkconf /etc/bind/named.conf 2>&1", $output, $return_var);
            
            if ($return_var !== 0) {
                $errorLog = implode("\n", $output);
                $pdo->prepare("UPDATE sys_dns_requests SET status = 'error', error_log = ?, processed_date = NOW() WHERE id = ?")->execute([$errorLog, $id]);
            } else {
                // f) Marcar completado
                $pdo->prepare("UPDATE sys_dns_requests SET status = 'completed', processed_date = NOW() WHERE id = ?")->execute([$id]);
                $reloadNeeded = true;
            }
        }
        
    } catch (Exception $e) {
        $error = $e->getMessage();
        $pdo->prepare("UPDATE sys_dns_requests SET status = 'error', error_log = ?, processed_date = NOW() WHERE id = ?")->execute([$error, $req['id']]);
    }
    
    // Optimización 1GB RAM: Desreferenciar arrays grandes tras iterar
    unset($records);
    unset($output);
    unset($req);
}

// 4. Aplicar Cambios Globales (si hubo cambios válidos y exitosos)
if ($reloadNeeded) {
    exec("rndc reload");
}

flock($lockHandle, LOCK_UN);
fclose($lockHandle);
?>
